apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-controllers/ClusterRole-crd-controller-flux-system.yml
- flux-controllers/ClusterRole-flux-edit-flux-system.yml
- flux-controllers/ClusterRole-flux-view-flux-system.yml
- flux-controllers/ClusterRoleBinding-cluster-reconciler-flux-system.yml
- flux-controllers/ClusterRoleBinding-crd-controller-flux-system.yml
- flux-controllers/CustomResourceDefinition-alerts.notification.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-buckets.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-externalartifacts.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-gitrepositories.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-helmcharts.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-helmreleases.helm.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-helmrepositories.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-kustomizations.kustomize.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-ocirepositories.source.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-providers.notification.toolkit.fluxcd.io.yml
- flux-controllers/CustomResourceDefinition-receivers.notification.toolkit.fluxcd.io.yml
- flux-controllers/Deployment-helm-controller.yml
- flux-controllers/Deployment-kustomize-controller.yml
- flux-controllers/Deployment-notification-controller.yml
- flux-controllers/Deployment-source-controller.yml
- flux-controllers/Namespace.yml
- flux-controllers/NetworkPolicy-allow-egress.yml
- flux-controllers/NetworkPolicy-allow-scraping.yml
- flux-controllers/NetworkPolicy-allow-webhooks.yml
- flux-controllers/ResourceQuota.yml
- flux-controllers/Service-notification-controller.yml
- flux-controllers/Service-source-controller.yml
- flux-controllers/Service-webhook-receiver.yml
- flux-controllers/ServiceAccount-helm-controller.yml
- flux-controllers/ServiceAccount-kustomize-controller.yml
- flux-controllers/ServiceAccount-notification-controller.yml
- flux-controllers/ServiceAccount-source-controller.yml
- flux-sync/GitRepository.yml
- flux-sync/self-sync.yml
- gotk-components.yaml
- gotk-sync.yaml
