apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../apps/apps-sync.yml
  - ../infra/config-sync.yml
  - ../infra/controller-sync.yml
  - ../infra/crds-sync.yml
