# yaml-language-server: $schema=../../../values-schemas/k8up/helmrelease.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: k8up
  targetNamespace: k8up
  chart:
    spec:
      chart: k8up
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: k8up
      interval: 6h
  values:
    metrics:
      serviceMonitor:
        enabled: true
      grafanaDashboard:
        enabled: true
