---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controller
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 2m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/controller
  prune: true
  wait: true
  patches:
    - patch: |-
        - op: add
          path: /spec/driftDetection
          value:
            mode: warn
            ignore:
              - paths: ["/spec/replicas"]
                target:
                  kind: Deployment
              - paths: ["/status"]
                target:
                  kind: Certificate
                  group: cert-manager.io
        - op: add
          path: /spec/install
          value:
            createNamespace: false
            remediation:
              retries: 3
            crds: CreateReplace
        - op: add
          path: /spec/upgrade
          value:
            force: true
            remediation:
              retries: 3
            crds: Skip
        - op: add
          path: /spec/test
          value:
            enable: true
            ignoreFailures: false
      target:
        kind: HelmRelease
        group: helm.toolkit.fluxcd.io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controller
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/config
  prune: true
