# yaml-language-server: $schema=../../../values-schemas/flagger/helmrelease.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: flagger
  targetNamespace: flagger
  chart:
    spec:
      chart: flagger
      version: 1.42.0
      sourceRef:
        kind: HelmRepository
        name: flagger
      interval: 6h
  values:
    leaderElection:
      enabled: true
      replicaCount: 3
    podDisruptionBudget:
      enabled: true
    prometheus:
      install: false
    meshProvider: gatewayapi:v1
    serviceMonitor:
      enabled: true
    metricsServer: http://monitoring-prometheus.monitoring:9090
  dependsOn:
    - name: cert-manager
    - name: cilium
    - name: longhorn
    - name: openbao
    - name: external-secrets
    - name: external-dns
    - name: kube-prometheus-stack
