---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: grafana-credentials #secret in cluster
  data:
    - secretKey: password #secretKey in cluster
      remoteRef:
        key: grafana-credentials #key in provider
        property: password #property in provider
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: user #secretKey in cluster
      remoteRef:
        key: grafana-credentials #key in provider
        property: user #property in provider
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
