---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-credentials
spec:
  refreshTime: 24h
  externalSecretName: ghcr-credentials
  externalSecretSpec:
    target:
      name: ghcr-credentials #secret in cluter
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
    data:
      - secretKey: password #secretKey in cluster
        remoteRef:
          key: ghcr-credentials #key in provider
          property: password #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
      - secretKey: username #secretKey in cluster
        remoteRef:
          key: ghcr-credentials #key in provider
          property: username #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
  # when using ClusterExternalSecret, you can specify which namespaces can access the secret in this way:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - vscode-server
