---
apiVersion: v1
kind: Namespace
metadata:
  name: vscode-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vscode-server
  namespace: flux-system
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/dmuiX/vscode-server-dockerized/main/charts
  secretRef:
    name: ghcr-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vscode-server
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: vscode-server
      version: 2026.04.01-fc23f2d # renovate: skip
      sourceRef:
        kind: HelmRepository
        name: vscode-server
      interval: 6h
  values:
    image:
      repository: ghcr.io/dmuix/vscode-server-dockerized
    imagePullSecrets:
      - name: ghcr-credentials
    limits:
      cpu: 1000m
    user:
      existingSecret: vscode-server-credentials
      userKey: username
      passwordKey: password
  releaseName: vscode-server
  targetNamespace: vscode-server
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
