---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vscode-server-credentials
  namespace: vscode-server
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: vscode-server-credentials #secret in cluster
  data:
    - secretKey: password #secretKey in cluster
      remoteRef:
        key: vscode-server-credentials #key in provider
        property: password #property in provider
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
    - secretKey: username #secretKey in cluster
      remoteRef:
        key: vscode-server-credentials #key in provider
        property: username #property in provider
        decodingStrategy: None # can be None, Base64, Base64URL or Auto
