---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 6h
  values:
    crds:
      enabled: true
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
    enableCertificateOwnerRef: true # will delete secrets when certificate ressource is deleted
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io