---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: cilium
  targetNamespace: cilium
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 6h
  values:
    ipam:
      mode: kubernetes
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: 7445
    sysctlfix:
      enabled: false
    installCRDs: true
    externalIPs:
      enabled: true
    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
      secretsNamespace:
        name: cilium
    envoy:
      enabled: true
    loadBalancer:
      l7:
        backend: envoy
      secretsNamespace:
        name: cilium
    l2announcements:
      enabled: true
    hubble:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
