---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: cilium
  targetNamespace: cilium
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 1m0s
  values:
    ipam:
      mode: kubernetes
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: 7445
    sysctlfix:
      enabled: false
    installCRDs: true
    externalIPs:
      enabled: true
    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
      secretsNamespace:
        name: cilium
    envoy:
      enabled: true
    envoyConfig:
      enabled: true
      secretsNamespace:
        name: cilium
    l2announcements:
      enabled: true
    l2podAnnouncements:
      enabled: true
      interface: ens3
    loadBalancer:
      l7:
        backend: envoy
    debug:
      enabled: true
      verbose: flow
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction"
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
