---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: external-dns
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 6h
  values:
    domainFilters:
      - k8sdev.cloud
    sources:
      - gateway-tlsroute
      - gateway-httproute
      - gateway-udproute
    logLevel: debug
    txtPrefix: external-dns
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        valueFrom:
          secretKeyRef:
            name: pihole
            key: EXTERNAL_DNS_PIHOLE_SERVER
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        valueFrom:
          secretKeyRef:
            name: pihole
            key: EXTERNAL_DNS_PIHOLE_API_VERSION
    provider: pihole
    registry: noop
    policy: upsert-only
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
  dependsOn:
    - name: cilium
