---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 6h
  values:
    installCRDs: true
    replicaCount: 2
    certManager:
      enabled: true
      cert:
        issuer:
          kind: ClusterIssuer
          name: letsencrypt
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
  dependsOn:
    - name: cert-manager
    - name: cilium
    - name: longhorn
    - name: external-dns
    - name: openbao
