---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 6h
  values:
    installCRDs: true
    replicaCount: 2
    certManager:
      enabled: true
      cert:
        issuer:
          kind: ClusterIssuer
          name: letsencrypt
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
  dependsOn:
    - name: cert-manager
    - name: cilium
    - name: longhorn
    - name: external-dns
    - name: openbao
    - name: external-secrets
