---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.36.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
      interval: 1m0s
  values:
    config:
      watchPlugins: true
    persistentVolumeClaim:
      enable: true
      size: 10Gi
      storageClassName: longhorn
    pluginManager:
      enabled: true
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
  dependsOn:
    - name: cilium
    - name: cert-manager
    - name: longhorn
