---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeseal-webui
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubeseal-webui
  namespace: flux-system
spec:
  interval: 24h
  url: https://jaydee94.github.io/kubeseal-webgui/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeseal-webui
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: kubeseal-webui
  targetNamespace: kubeseal-webui
  chart:
    spec:
      chart: kubeseal-webui
      version: 6.0.4
      sourceRef:
        kind: HelmRepository
        name: kubeseal-webui
      interval: 6h
  values:
    sealedSecrets.autoFetchCert: true
    sealedSecrets.controllerName: sealed-secrets-controller
    sealedSecrets.controllerNamespace: sealed-secrets
