---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: loki
  targetNamespace: monitoring
  chart:
    spec:
      chart: loki
      version: 9.3.3
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 6h
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    monitoring:
      serviceMonitor:
        enabled: true
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
  dependsOn:
    - name: kube-prometheus-stack
    - name: longhorn
