---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: longhorn
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 1m0s
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: "2"  # You have 2 workers
      createDefaultDiskLabeledNodes: false  # Manual node selection
      guaranteedInstanceManagerCPU: "12"

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2 # Match worker count
      reclaimPolicy: Retain

    service:
      ui:
        type: ClusterIP

    # Schedule Longhorn manager ONLY on worker nodes
    longhornManager:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"

    # Schedule Longhorn driver ONLY on worker nodes
    longhornDriver:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"

    # Schedule Longhorn UI ONLY on worker nodes
    longhornUI:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
