---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: longhorn
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 6h
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: "2"
      createDefaultDiskLabeledNodes: "false"
      guaranteedInstanceManagerCPU: "12"
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    service:
      ui:
        type: ClusterIP
    longhornManager:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
    longhornDriver:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
    longhornUI:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
  install:
    createNamespace: false # Namespace created separately with PSA labels
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
  dependsOn:
    - name: cilium
    - name: cert-manager
