---
apiVersion: v1
kind: Namespace
metadata:
  name: opencost
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 24h
  url: https://opencost.github.io/opencost-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: opencost
  targetNamespace: opencost
  chart:
    spec:
      chart: opencost
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: opencost
      interval: 6h
  values:
    opencost:
      prometheus:
        internal:
          namespaceName: monitoring
          serviceName: monitoring-prometheus
          port: 9090
      dataRetention:
        dailyResolutionDays: 30 # default: 15
      exporter:
        defaultClusterId: talos-k8sdev
        replicas: 2
        resources:
          requests:
            cpu: "10m"
            memory: "55Mi"
          limits:
            memory: "1Gi"
        persistence:
          enabled: true
          storageClass: longhorn # adjust based on your environment
          accessMode: ReadWriteMany
          size: 5Gi
      customPricing:
        enabled: true
        provider: aws
        costModel:
          description: Modified pricing configuration.
          CPU: 0.031611
          spotCPU: 0.006655
          RAM: 0.004237
          spotRAM: 0.000892
          GPU: 0.95
          storage: 0.00005479452
          zoneNetworkEgress: 0.01
          regionNetworkEgress: 0.01
          internetNetworkEgress: 0.143
          spotLabel: ""
          spotLabelValue: ""
          awsServiceKeyName: ""
          awsServiceKeySecret: ""
          awsSpotDataRegion: ""
          awsSpotDataBucket: ""
          awsSpotDataPrefix: ""
          athenaBucketName: ""
          athenaRegion: ""
          athenaDatabase: ""
          athenaTable: ""
          projectID: "${ACCOUNT_ID}"
      metrics:
        kubeStateMetrics:
          emitKsmV1Metrics: false
          emitKsmV1MetricsOnly: false
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
      ui:
        enabled: true
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: false
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
  dependsOn:
    - name: cilium
    - name: cert-manager
    - name: longhorn
