---
apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: flux-system
spec:
  releaseName: openbao
  targetNamespace: openbao
  chart:
    spec:
      chart: openbao
      version: 0.18.4
      sourceRef:
        kind: HelmRepository
        name: openbao
      interval: 1m0s
  values:
    server:
      auditStorage:
        accessMode: ReadWriteMany
        storageClass: longhorn
      dataStorage:
        accessMode: ReadWriteMany
        storageClass: longhorn
      # --- Define the Volume to be mounted from the Secret ---
      volumes:
        # A logical name for the volume
        - name: unseal-key-volume
          secret:
            # The name of the Kubernetes Secret resource to use
            secretName: openbao-unseal-key
            # Explicitly state which keys from the secret to mount
            # This makes the configuration very clear and prevents other keys
            # in the secret from being mounted accidentally.
            items:
              # The data key within the secret
              - key: unseal-key
                # The filename to create inside the volume
                path: unseal-key
      # --- Mount the Volume into the Container ---
      volumeMounts:
        - name: unseal-key-volume
          # The directory inside the pod
          mountPath: /openbao/secrets
          readOnly: true
      ha:
        enabled: true
        replicas: 2
        raft:
          enabled: true
          setNodeId: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          service_registration "kubernetes" {}

          # Example configuration for using auto-unseal using static ENV keys.
          seal "static" {
            current_key_id = "20251013"
            current_key = "file:///openbao/secrets/unseal-key"
          }

          # Example configuration for enabling Prometheus metrics.
          # If you are using Prometheus Operator you can enable a ServiceMonitor resource below.
          # You may wish to enable unauthenticated metrics in the listener block above.
          telemetry {
            prometheus_retention_time = "30s"
            disable_hostname = true
          }
      resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    ui:
      enabled: true
  dependsOn:
    - name: cilium
    - name: cert-manager
    - name: external-dns
    - name: longhorn
