---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: openbao
  targetNamespace: openbao
  chart:
    spec:
      chart: openbao
      version: 0.18.4
      sourceRef:
        kind: HelmRepository
        name: openbao
      interval: 1m0s
  values:
    server:
      auditStorage:
        accessMode: ReadWriteMany
        storageClass: longhorn
      dataStorage:
        accessMode: ReadWriteMany
        storageClass: longhorn
      # extraSecretEnvironmentVars:
      #   - envName: STATIC_UNSEAL_KEY
      #     secretName: unseal-keys
      #     secretKey: key
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
        replicas: 2
        # config: |
        #   ui = true

        #   listener "tcp" {
        #     tls_disable = 1
        #     address = "[::]:8200"
        #     cluster_address = "[::]:8201"
        #   }

        #   service_registration "kubernetes" {}

        #   # Example configuration for using auto-unseal using static ENV keys.
        #   seal "static" {
        #     current_key_id = 20251011
        #     current_key = "env:STATIC_UNSEAL_KEY"
        #     disabled        = "false"
        #   }

        #   # Example configuration for enabling Prometheus metrics.
        #   # If you are using Prometheus Operator you can enable a ServiceMonitor resource below.
        #   # You may wish to enable unauthenticated metrics in the listener block above.
        #   telemetry {
        #     prometheus_retention_time = "30s"
        #     disable_hostname = true
        #   }
    ui:
      enabled: true
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      # HPA-managed replicas
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
      # Certificate timestamps that change
      - paths: ["/status"]
        target:
          kind: Certificate
          group: cert-manager.io
  dependsOn:
    - name: cilium
    - name: cert-manager
    - name: longhorn
