---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-token
spec:
  refreshTime: 24h
  externalSecretName: "cloudflare-token"
  externalSecretSpec:
    target:
      name: cloudflare-token
    dataFrom:
      - extract:
          key: cloudflare-token
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
  # when using ClusterExternalSecret, you can specify which namespaces can access the secret in this way:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - cert-manager
            - external-dns
