---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-credentials
  namespace: flux-system
spec:
  refreshTime: 30m
  externalSecretName: ghcr-credentials
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
    target:
      name: ghcr-credentials #secret in cluter
    data:
      - secretKey: password #secretKey in cluster
        remoteRef:
          key: ghcr-credentials #key in provider
          property: password #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
      - secretKey: username #secretKey in cluster
        remoteRef:
          key: ghcr-credentials #key in provider
          property: username #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - vscode-server
            - flux-system
