---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-token
spec:
  refreshTime: 24h
  externalSecretName: "cloudflare-token"
  externalSecretSpec:
    target:
      name: cloudflare-token #secret in cluter
    data:
      - secretKey: token #secretKey in cluster
        remoteRef:
          key: cloudflare-token #key in provider
          property: token #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
  # when using ClusterExternalSecret, you can specify which namespaces can access the secret in this way:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - cert-manager
            - external-dns
