---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: r2-credentials
spec:
  refreshTime: 24h
  externalSecretName: r2-credentials
  externalSecretSpec:
    target:
      name: r2-credentials #secret in cluter
    data:
      - secretKey: access-key-id #secretKey in cluster
        remoteRef:
          key: r2-credentials #key in provider
          property: access-key-id #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
      - secretKey: secret-access-key #secretKey in cluster
        remoteRef:
          key: r2-credentials #key in provider
          property: secret-access-key #property in provider
          decodingStrategy: None # can be None, Base64, Base64URL or Auto
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
  # when using ClusterExternalSecret, you can specify which namespaces can access the secret in this way:
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - k8up
