---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: openbao-k8up-schedule
  namespace: openbao
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: k8up-repo-password
      key: password
    s3:
      endpoint: https://e7b3567ace974b8838999da5f1858701.eu.r2.cloudflarestorage.com
      bucket: k8sdev-backups
      accessKeyIDSecretRef:
        name: r2-credentials
        key: access-key-id
      secretAccessKeySecretRef:
        name: r2-credentials
        key: secret-access-key
  backup:
    schedule: "0 2 * * *" # daily @2:00
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    promURL: http://prometheus-pushgateway.monitoring:9091
  check:
    schedule: "0 1 * * 1" # on each monday @ 1:00
    promURL: http://prometheus-pushgateway.monitoring:9091
  prune:
    schedule: "0 1 * * 0" # on each sunday @ 1:00
    retention:
      keepLast: 5
      keepDaily: 14
