# yaml-language-server: $schema=../../../values-schemas/opencost/helmrelease.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: opencost
  targetNamespace: opencost
  chart:
    spec:
      chart: opencost
      version: 2.5.14
      sourceRef:
        kind: HelmRepository
        name: opencost
      interval: 6h
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: PersistentVolumeClaim
              name: opencost-pvc
            patch: "- op: add

              \  path: /metadata/annotations/helm.sh~1resource-policy

              \  value: keep\n"
  values:
    opencost:
      prometheus:
        internal:
          namespaceName: monitoring
          serviceName: monitoring-prometheus
          port: 9090
      exporter:
        defaultClusterId: talos-k8sdev
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteMany
          size: 5Gi
      customPricing:
        enabled: true
        provider: aws
      metrics:
        kubeStateMetrics:
          emitKsmV1Metrics: false
          emitKsmV1MetricsOnly: false
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
      ui:
        enabled: true
  dependsOn:
    - name: cert-manager
    - name: cilium
    - name: longhorn
    - name: openbao
    - name: external-secrets
    - name: external-dns
    - name: kube-prometheus-stack
