apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.*.*"
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 5m
  values:
    replicaCount: 2
  releaseName: podinfo
  targetNamespace: podinfo
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
